<?php
// if called directly, abort.
if (!defined('WPINC')) { die; }

class raysgrid_Config {
    
    public $settings;
    
    public function __construct() {
        add_action('init', array(&$this, 'rsgd_configs'));
    }
    
    public function rsgd_configs() {
        $this->settings = array(
            array(
                "name" => "id",
                "title" => "id",
                "data_type" => "mediumint(9)",
                "type" => "int",
                "auto" => "AUTO_INCREMENT",
                "not_null" => "NOT NULL",
            ),
            /* Start Naming */
            array(
                "name" => "title",
                "title" => "Title",
                "data_type" => "text",
                "type" => "text",
                "section" => "rsgd_naming",
                "not_null" => "NOT NULL",
                "description" => "Insert the grid title.",
            ),
            array(
                "name" => "alias",
                "title" => "Alias",
                "data_type" => "text",
                "type" => "text",
                "class" => "alias_txt",
                "section" => "rsgd_naming",
                "not_null" => "NOT NULL",
                "description" => "Insert the grid alias.",
            ),
            array(
                "name" => "shortcode",
                "title" => "Shortcode",
                "data_type" => "text",
                "type" => "disabledtext",
                "class" => "shortcode_txt",
                "section" => "rsgd_naming",
                "not_null" => "NOT NULL",
                "description" => "Shortcode will be generated automatically once you type the alias.",
            ),
            array(
                "name" => "extra_class",
                "title" => "Extra CSS Class",
                "data_type" => "text",
                "type" => "text",
                "section" => "rsgd_naming",
                "not_null" => "NULL",
                "description" => "Add extra css class name and refer to it in custom CSS.",
            ),
            array(
                "name" => "oldalias",
                "data_type" => "text",
                "type" => "hidden",
                "section" => "rsgd_naming",
                "not_null" => "NULL",
            ),
            /* Start Source */
            array(
                "name" => "post_type",
                "title" => "Post Types",
                "data_type" => "text",
                "type" => "multidropdown",
                "choices" => rsgd_post_types(),
                "section" => "rsgd_source",
                "not_null" => "NULL",
                "description" => "Select from available post types.",
                "std" => "octa",
            ),
            array(
                "name" => "select_taxonomy",
                "title" => "Post Categories",
                "data_type" => "text",
                "type" => "taxsdropdown",
                "section" => "rsgd_source",
                "not_null" => "NULL",
                "description" => "Select from available categories or tags.",
            ),
            array(
                "name" => "maximum_entries",
                "title" => "Maximun Entries",
                "data_type" => "int",
                "type" => "number",
                "section" => "rsgd_source",
                "not_null" => "NULL",
                "description" => "Leave it (-1) if you want to show all portfolio posts.",
                "placeholder" => "-1",
                "std" => "-1",
                "min" => "-1",
                "max" => "100",
            ),
            array(
                "name" => "order_by",
                "title" => "Order By ",
                "data_type" => "text",
                "type" => "dropdown",
                "class" => "rsgd_select_boxes",
                "choices" => array(
                    'date' => 'Date',
                    'title' => 'Title',
                    'id' => 'Id',
                    'name' => 'Name',
                    'modified' => 'Modified',
                    'author' => 'Author',
                ),
                "section" => "rsgd_source",
                "not_null" => "NULL",
                "description" => "Select the grids order from the available options.",
            ),
            array(
                "name" => "order_type",
                "title" => "Order Type",
                "data_type" => "text",
                "type" => "dropdown",
                "class" => "rsgd_select_boxes",
                "choices" => array(
                    'desc' => 'Descending',
                    'asc' => 'Ascending',
                ),
                "section" => "rsgd_source",
                "not_null" => "NULL",
                "description" => "Order posts ascending or descending.",
            ),
            array(
                "name" => "image_source",
                "title" => "Image Source Type",
                "data_type" => "text",
                "class" => "rsgd_select_boxes",
                "type" => "dropdown",
                "choices" => array(
                    'full' => 'Full',
                    'thumbnail' => 'Thumbnail',
                    'medium' => 'Medium',
                    'medium_large' => 'Medium Large',
                    'large' => 'Large',
                ),
                "section" => "rsgd_source",
                "not_null" => "NULL",
                "description" => "Choose what image size to be set to the image in the grid items.",
            ),
            array(
                "name" => "pagination_type",
                "title" => "Pagination",
                "data_type" => "text",
                "class" => "rsgd_select_boxes",
                "type" => "dropdown",
                "choices" => array(
                    'enable' => 'Enable',
                    'smart' => 'Smart Loading',
                ),
                "section" => "rsgd_source",
                "not_null" => "NULL",
            ),
            array(
                "name" => "pagination_style",
                "title" => "Smart Loading",
                "data_type" => "text",
                "class" => "rsgd_select_boxes",
                "type" => "dropdown",
                "choices" => array(
                    'infinite' => 'Infinite Scroll',
                    'loadmore' => 'Load More Button',
                ),
                "section" => "rsgd_source",
                "not_null" => "NULL",
                "description" => "Choose pagination smart loading type.",
                'dependency' => array(
                    'element' => 'pagination_type',
                    'value' => 'smart'
                ),
            ),
            array(
                "name" => "load_more_button_text",
                "title" => "Load More Button Text",
                "data_type" => "text",
                "type" => "text",
                "section" => "rsgd_source",
                "not_null" => "NULL",
                "description" => "Align the pager below the grids horizontally.",
                'dependency' => array(
                    'element' => 'pagination_style',
                    'value' => 'loadmore'
                ),
                "placeholder" => "Load More",
                "std" => "Load More",
            ),
            array(
                "name" => "items_per_page",
                "title" => "Max. Visible Rows",
                "data_type" => "int",
                "type" => "number",
                "section" => "rsgd_source",
                "not_null" => "NULL",
                "description" => "Number of visible rows.",
                "placeholder" => "9",
                "std" => "9",
                "min" => "0",
                "max" => "500",
                'dependency' => array(
                    'element' => 'pagination_type',
                    'value' => 'enable'
                ),
            ),
            array(
                "name" => "items_start",
                "title" => "Visible Items",
                "data_type" => "int",
                "type" => "number",
                "section" => "rsgd_source",
                "not_null" => "NULL",
                "description" => "Number of visible Items On Load.",
                "placeholder" => "3",
                "std" => "3",
                "min" => "3",
                "max" => "100",
                'dependency' => array(
                    'element' => 'pagination_type',
                    'value' => 'smart'
                ),
            ),
            array(
                "name" => "pagination_alignment",
                "title" => "Button Alignment",
                "data_type" => "text",
                "class" => "rsgd_select_boxes",
                "type" => "dropdown",
                "choices" => array(
                    'center' => 'Center',
                    'left' => 'Left',
                    'right' => 'Right',
                ),
                "section" => "rsgd_source",
                "not_null" => "NULL",
                "description" => "Align the load more button.",
                'dependency' => array(
                    'element' => 'pagination_style',
                    'value' => 'loadmore'
                ),
            ),
            /* Start Grid Setting */
            array(
                "name" => "main_color",
                "title" => "Main Color",
                "data_type" => "text",
                "type" => "color",
                "section" => "rsgd_gnrlsetting",
                "not_null" => "NULL",
                "placeholder" => "#7da600",
                "std" => "#7da600",
            ),
            array(
                "name" => "grid_layout",
                "title" => "Grid Layout",
                "data_type" => "text",
                "type" => "dropdown",
                "class" => "rsgd_select_boxes",
                "section" => "rsgd_gnrlsetting",
                "not_null" => "NULL",
                "choices" => array(
                    'grid' => 'Even',
                    'masonry' => 'Masonry',
                    //'justify' => 'Dynamic Width',
                    'onecolumn' => 'One Column',
                    'slider' => 'Slider',
                ),
                "description" => "Choose how the grid will appear for users.",
                "std" => "grid",
            ),
            array(
                "name" => "img_ratio",
                "title" => "Media Ratio X:Y",
                "data_type" => "text",
                "type" => "twonumber",
                "section" => "rsgd_gnrlsetting",
                "not_null" => "NULL",
                "placeholder" => "5|4",
                "std" => "5|4",
                'dependency' => array(
                    'element' => 'grid_layout',
                    'value' => 'grid'
                ),
            ),
            array(
                "name" => "slider_type",
                "title" => "Slider Type",
                "data_type" => "text",
                "type" => "dropdown",
                "section" => "rsgd_gnrlsetting",
                "not_null" => "NULL",
                "class" => "rsgd_select_boxes",
                "choices" => array(
                    'horizontal' => 'Horizontal',
                    'vertical' => 'Vertical',
                ),
                "std" => "horizontal",
                'dependency' => array(
                    'element' => 'grid_layout',
                    'value' => 'slider'
                ),
            ),
            array(
                "name" => "slide_to_show",
                "title" => "Slides To Show",
                "data_type" => "int",
                "type" => "number",
                "section" => "rsgd_gnrlsetting",
                "not_null" => "NULL",
                "placeholder" => "4",
                "description" => "Enter the number of slides to be shown.",
                "std" => "4",
                "min" => "1",
                "max" => "10",
                'dependency' => array(
                    'element' => 'grid_layout',
                    'value' => 'slider'
                ),
            ),
            array(
                "name" => "slide_to_scroll",
                "title" => "Slide To Scroll",
                "data_type" => "int",
                "type" => "number",
                "section" => "rsgd_gnrlsetting",
                "not_null" => "NULL",
                "placeholder" => "1",
                "description" => "Number of slides that will be scrolled.",
                "std" => "1",
                "min" => "1",
                "max" => "10",
                'dependency' => array(
                    'element' => 'grid_layout',
                    'value' => 'slider'
                ),
            ),
            array(
                "name" => "slide_speed",
                "title" => "Slide Speed",
                "data_type" => "int",
                "type" => "number",
                "section" => "rsgd_gnrlsetting",
                "not_null" => "NULL",
                "placeholder" => "500",
                "description" => "Speed of the slider in milliseconds.",
                "std" => "500",
                "min" => "0",
                "max" => "1000",
                'dependency' => array(
                    'element' => 'grid_layout',
                    'value' => 'slider'
                ),
            ),
            array(
                "name" => "fade",
                "title" => "Fade ?",
                "data_type" => "text",
                "type" => "checkbox",
                "section" => "rsgd_gnrlsetting",
                "not_null" => "NULL",
                "std" => "",
                'dependency' => array(
                    'element' => 'grid_layout',
                    'value' => 'slider'
                ),
            ),
            array(
                "name" => "auto_play",
                "title" => "Auto Play ? ",
                "data_type" => "text",
                "type" => "checkbox",
                "section" => "rsgd_gnrlsetting",
                "not_null" => "NULL",
                "std" => "",
                'dependency' => array(
                    'element' => 'grid_layout',
                    'value' => 'slider'
                ),
            ),
            array(
                "name" => "show_arrows",
                "title" => "Show Arrows ? ",
                "data_type" => "text",
                "type" => "checkbox",
                "section" => "rsgd_gnrlsetting",
                "not_null" => "NULL",
                "std" => "1",
                'dependency' => array(
                    'element' => 'grid_layout',
                    'value' => 'slider'
                ),
            ),
            array(
                "name" => "show_bullets",
                "title" => "Show Bullets ? ",
                "data_type" => "text",
                "type" => "checkbox",
                "section" => "rsgd_gnrlsetting",
                "not_null" => "NULL",
                "std" => "",
                'dependency' => array(
                    'element' => 'grid_layout',
                    'value' => 'slider'
                ),
            ),
            array(
                "name" => "infinite",
                "title" => "Infinite ? ",
                "data_type" => "text",
                "type" => "checkbox",
                "section" => "rsgd_gnrlsetting",
                "not_null" => "NULL",
                "std" => "1",
                'dependency' => array(
                    'element' => 'grid_layout',
                    'value' => 'slider'
                ),
            ),
            array(
                "name" => "number_of_columns",
                "title" => "Columns Per Row",
                "data_type" => "text",
                "type" => "dropdown",
                "class" => "rsgd_select_boxes",
                "section" => "rsgd_gnrlsetting",
                "choices" => array(
                    '2' => '2 Columns',
                    '3' => '3 Columns',
                    '4' => '4 Columns',
                    '5' => '5 Columns',
                    '6' => '6 Columns',
                ),
                "std" => "4",
                "not_null" => "NULL",
                "description" => "Items per row that will be shown horizontally.",
                'dependency' => array(
                    'element' => 'grid_layout',
                    'value' => array('grid','masonry','slider')
                ),
            ),
            array(
                "name" => "item_spacing",
                "title" => "Item Spacing",
                "data_type" => "int",
                "type" => "number",
                "section" => "rsgd_gnrlsetting",
                "not_null" => "NULL",
                "description" => "Enter the Spacing between grid items.",
                "placeholder" => "15",
                "std" => "15",
                "min" => "0",
                "max" => "100",
            ),
            array(
                "name" => "preloader",
                "title" => "Pre-loader",
                "data_type" => "text",
                "type" => "dropdown",
                "choices" => array(
                    '-1' => 'None',
                    'cp-round' => 'Spinner Round',
                    'cp-pinwheel' => 'Spinner Pinwheel',
                    'cp-balls' => 'Spinner Balls',
                    'cp-bubble' => 'Spinner Bubble',
                    'cp-flip' => 'Spinner Flip',
                    'cp-hue' => 'Spinner Hue',
                    'cp-skeleton' => 'Spinner Skeleton',
                    'cp-eclipse' => 'Spinner Eclipse',
                    'cp-boxes' => 'Spinner Boxes',
                    'cp-morph' => 'Spinner Morph',
                ),
                "section" => "rsgd_gnrlsetting",
                "not_null" => "NULL",
                "description" => "Select a preloading styles that appears before all grid items completely loaded.",
            ),
            array(
                "name" => "rtl",
                "title" => "RTL",
                "data_type" => "text",
                "type" => "checkbox",
                "section" => "rsgd_gnrlsetting",
                "not_null" => "NULL",
                "std" => "0",
            ),
            /* Start Skins & Styles */
            array(
                "name" => "choose_skin",
                "title" => "Choose Skin",
                "data_type" => "text",
                "type" => "radio",
                "choices" => array(
                    'kara' => 'Kara',
                    'hub' => 'Hub',
                    'ivy' => 'Ivy',
                    'krosh' => 'Krosh',
                    'impress' => 'Impress',
                    'transit' => 'Transit',
                    'neuron' => 'Neuron',
                    'onair' => 'OnAir',
                    'rotato' => 'Rotato',
                    'agent' => 'Agent',
                    'rolly' => 'Rolly',
                    'mass' => 'Mass',
                    'marbele' => 'Marble',
                    'astro' => 'Asrto',
                    
                    'paleo' => 'Paleo',
                    'sublime' => 'Sublime',
                    'resort' => 'Resort',
                    'gemini' => 'Gemini',
                    'solo' => 'Solo',
                    'focus' => 'Focus',
                    'zilla' => 'Zilla',
                    
                ),
                "class" => "portfolio-item",
                "section" => "rsgd_skins",
                "not_null" => "NULL",
                "std" => "p-style1",
            ),
            array(
                "name" => "show_title",
                "title" => "Show Title",
                "data_type" => "text",
                "type" => "checkbox",
                "section" => "rsgd_skins",
                "not_null" => "NULL",
                "std" => "1",
            ),
            array(
                "name" => "show_categories",
                "title" => "Show Taxonomies",
                "data_type" => "text",
                "type" => "checkbox",
                "section" => "rsgd_skins",
                "not_null" => "NULL",
                "std" => "1",
            ),
            array(
                "name" => "show_link_to_post",
                "title" => "Show Link to post",
                "data_type" => "text",
                "type" => "checkbox",
                "section" => "rsgd_skins",
                "not_null" => "NULL",
                "std" => "1",
            ),
            array(
                "name" => "show_zoom_image",
                "title" => "Show Zoom Image",
                "data_type" => "text",
                "type" => "checkbox",
                "section" => "rsgd_skins",
                "not_null" => "NULL",
                "std" => "1",
            ),
            array(
                "name" => "show_excerpt",
                "title" => "Show Excerpt",
                "data_type" => "text",
                "type" => "checkbox",
                "section" => "rsgd_skins",
                "not_null" => "NULL",
                "std" => "",
            ),
            
            /* Start Nav Filter */
            array(
                "name" => "nav_filter",
                "title" => "Nav-Filter",
                "data_type" => "text",
                "class" => "rsgd_select_boxes",
                "type" => "dropdown",
                "choices" => array(
                    'style1'    => 'Round Boxes',
                    'style2'    => 'Bottom Border',
                    'style3'    => 'Small Bottom Border',
                    'style4'    => 'Simple',
                    'style5'    => 'Top Bottom Borders',
                    'none'      => 'None',
                ),
                "section" => "rsgd_nav",
                "not_null" => "NULL",
                "description" => "Select Navigation filter style that appears at the top of the grids.",
            ),
            array(
                "name" => "show_all",
                "title" => "Show All Button",
                "data_type" => "text",
                "type" => "checkbox",
                "section" => "rsgd_nav",
                "not_null" => "NULL",
                "description" => "Show / Hide (All) button.",
                "std" => "1",
            ),
            array(
                "name" => "all_text",
                "title" => "Show All Button Text",
                "data_type" => "text",
                "type" => "text",
                "section" => "rsgd_nav",
                "not_null" => "NULL",
                "std" => "All",
                'dependency' => array(
                    'element' => 'show_all',
                    'value' => '1'
                ),
            ), 
            array(
                "name" => "nav_layout",
                "title" => "Layout Option",
                "data_type" => "text",
                "type" => "dropdown",
                "class" => "rsgd_select_boxes",
                "choices" => array(
                    'inline' => 'List',
                    'dropdown' => 'DropDown',
                ),
                "section" => "rsgd_nav",
                "not_null" => "NULL",
            ),
            array(
                "name" => "els_num",
                "title" => "Show Number of Elements",
                "data_type" => "text",
                "type" => "checkbox",
                "section" => "rsgd_nav",
                "not_null" => "NULL",
                "std" => "0",
            ),
            array(
                "name" => "num_style",
                "title" => "Numbers Style",
                "data_type" => "text",
                "class" => "rsgd_select_boxes",
                "type" => "dropdown",
                "choices" => array(
                    'inline' => 'Inline',
                    'popup' => 'Tooltip',
                ),
                'dependency' => array(
                    'element' => 'els_num',
                    'value' => '1'
                ),
                "section" => "rsgd_nav",
                "not_null" => "NULL",
            ),
            /* Start Custom Css */
            /*array(
                "name" => "custom_css",
                "title" => "Custom CSS",
                "data_type" => "text",
                "type" => "textarea",
                "class" => "custom_css",
                "section" => "rsgd_css",
                "not_null" => "NULL",
                "description" => "Add custom css code for this grid to give it a custom style.",
            ), */
        );
        return $this->settings;
    }
    
}
new raysgrid_Config();
